export const QUERY_KEYS = {
  COMPANIES: 'COMPANIES',
  COMPANY_DETAILS: 'COMPANY_DETAILS',
  SERVICE_OPTIONS: 'SERVICE_OPTIONS',
  USERS: 'USERS',
  USER_DETAILS: 'USER_DETAILS',
  EMPLOYEES: 'EMPLOYEES',
  ROLE_GROUPS: 'ROLE_GROUPS',
  LANGUAGES: 'LANGUAGES',
};
