#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo 'HUSKY xodlandı. :writing_hand: :writing_hand:   Git commit prosesi başlayır. :hourglass::hourglass::hourglass::hourglass::hourglass:'
# Check Prettier standards
npm run check-format ||
(
    echo 'PRETTIER FAILED :x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x:
    ƏZİZ DEVELOPERİM, Prettier-də xəta var. NPM RUN FORMAT command`ını işə sal sonra git commit et!';
    false;
)
# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLINT FAILED :x::x::x::x::x::x::x::x::x::x::x::x::x::x::x::x::x:
        ƏZİZ DEVELOPERİM, ESLint-də xəta var. Göstərilən faylda düzəlişi et, sonra git commit et!'
        false;
)
# Check tsconfig standards
npm run check-types ||
(
    echo 'TYPESCIRPT FAILED. :x::x::x::x::x::x::x::x::x::x::x::x::x::x::x::x::x:
            ƏZİZ DEVELOPERİM, Typescript xətası alıram. Göstərilən fayldakı xətanı düzəlt. ÇAŞIB ANY YAZMA, BU DƏFƏ ESLİNTDƏN KEÇMƏYƏCƏK.
            simple-import-sort xətası gəlirsə NPM RUN LINT_FIX commandını işə sal
            Daha sonra git commit et!'
    false;
)
# If everything passes... Now we can commit
echo ':v::v: OBAAAAAAA ESLint Prettier və TypeScriptdən kodların keçdi. Görək build prosesindən keçəçəkmi? :sparkles::sparkles::sparkles::sparkles:'
npm run build ||
(
    echo 'BUILD prosesində xəta var :x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x::hand::x:
    ƏZİZ DEVELOPERİM, Next build prosesində xəta baş verib. Bax gör nədir məsələ. Həll etdikdən sonra git commit et!
    '
    false;
)
# If everything passes... Now we can commit
echo ':heart::heart::heart::heart:  SƏN MUJİKSƏN... HUSKY prosesi uğurla başa çatdı . :white_check_mark::white_check_mark::white_check_mark::white_check_mark:'